[package]
name = "json_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
serde = { version = "1.0.223", features = ["derive"] }
serde_json = "1.0.145"
slotmap = "1.0.7"
